// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StocksReporting.Infrastructure;

#nullable disable

namespace StocksReporting.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(StocksReportingDbContext))]
    partial class StocksReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("StocksReporting.Domain.Email.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("EmailId");

                    b.HasKey("Id");

                    b.ToTable("Emails", (string)null);
                });

            modelBuilder.Entity("StocksReporting.Domain.Email.Email", b =>
                {
                    b.OwnsOne("StocksReporting.Domain.Email.ValueObjects.EmailValue", "EmailValue", b1 =>
                        {
                            b1.Property<Guid>("EmailId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("EmailId");

                            b1.ToTable("Emails");

                            b1.WithOwner()
                                .HasForeignKey("EmailId");
                        });

                    b.Navigation("EmailValue")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
