name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./StocksReporting.sln

    - name: Build solution
      run: dotnet build --no-restore ./StocksReporting.sln

    - name: Run tests
      run: dotnet test --no-build --verbosity normal ./StocksReporting.sln

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.8'

    - name: Install FE dependencies
      run: npm ci
      working-directory: ./reactfrontend

    - name: Build FE
      run: npm run build
      working-directory: ./reactfrontend
