name: CI

on:
  push:
    branches: [ main, develop, feature/deploy ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./StocksReporting.sln

    - name: Build solution
      run: dotnet build --no-restore ./StocksReporting.sln

    - name: Run tests
      run: dotnet test --no-build --verbosity normal ./StocksReporting.sln

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.8'

    - name: Install FE dependencies
      run: npm ci
      working-directory: ./reactfrontend

    - name: Build FE
      run: npm run build
      working-directory: ./reactfrontend

  deploy:
    name: Publish & Deploy to Azure
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 1) Publish your ASP.NET Core web project into a local folder named "publish-output"
      - name: Publish .NET WebAPI
        run: |
          dotnet publish StocksReporting/StocksReporting.Web.csproj \
            --configuration Release \
            --output ./publish-output

      # 2) Deploy that "publish-output" folder to your Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'PV260'                # e.g. "my-stocks-reporting-api"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish-output'